---
# Common configuration
router_name: "lxcbr0"
nat_name: "{{ ansible_default_ipv4['alias'] }}"
ansible_path: "{{ playbook_dir | replace('/ansible', '') }}"
ssh_key_location: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
inner_if_name: eth1
router_network: '10.1.0.0'
router_ip: '10.1.0.1'

# Base domain name
domain: 'example.com'

general_container_config:
  - 'lxc.network.ipv4 = {{ item.ip }}/16'
  - 'lxc.network.ipv4.gateway = {{ router_ip }}'
  - 'lxc.mount.entry={{ ansible_path }} vagrant/ none bind 0 0'
  - 'lxc.kmsg = 0'

# Development containers
containers:
  - name: "{{ hostname_prefix }}-test1"
    ip: '10.1.1.1'
    ssh_port: '2201'
    running_id: 0
  - name: "{{ hostname_prefix }}-test2"
    ip: '10.1.2.1'
    ssh_port: '2203'
    running_id: 1
  - name: "{{ hostname_prefix }}-test3"
    ip: '10.1.3.1'
    ssh_port: '2202'
    running_id: 2

# Development additional ports
additional_ports:
  - name: '80 to Test1'
    from: "{{ inner_if_name }}"
    to: '10.1.1.1'
    inner: 80
    outer: 80
  - name: '443 to Test1'
    from: "{{ inner_if_name }}"
    to: '10.1.1.1'
    inner: 443
    outer: 443
